---
- hosts: all
  
  tasks:
  
  - name: Copy dockerfile to remote machine
    copy:
     src: dockerfile
     dest: .
     
  - name: Copy war file to remote machine
    copy:
     src: webapp.war
     dest: .
  
  - name: stop running container
    command: docker stop customcontainer
    ignore_errors: True
    
  - name: remove container
    command: docker rm customcontainer
    ignore_errors: True
    
  - name: remove customimage
    command: docker rmi customimage
    ignore_errors: true
    
  - name: build customimage
    command: docker build -t customimage .
    
  - name: run the container and deploy the app
    command: docker run -d -p 8080:8080 --name customcontainer customimage
